# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-21 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'courses'},
        ),
    ]
