# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-29 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_auto_20200421_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.Chapitre')),
            ],
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='num',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='total_students',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(default='', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='Quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.Quiz'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.Course'),
        ),
    ]
